title: It's Airborne!
description: "Timeline supporting the aerosol nature of COVID-19 transmission"
year: 2020
author: various contributors
# add search box to navbar, true/false
search: false
markdown: kramdown

#######
# Defaults 
# to simplify front matter
# all files in the "pages" folder will be output at root of site
defaults:
  - scope:
      path: "pages"
    values:
      layout: page
      permalink: /:basename:output_ext

# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
